### ISSUE TITLE
Add npm start and npm watch scripts

### ISSUE THREAD

**Issue by sibelius** [reergymerej/npm-boom#8]

**Comment by reergymerej** [comment]
Good idea. I merged the start script already. Thanks!

**Comment by sibelius** [comment]
We can use nodemon or babel-watch for the watch script

**Comment by reergymerej** [comment]
On second thought, do we need any watchers? Maybe for running lint. 

npm test -- --watch
will rebuild in memory on file change and run the tests

npm publish
will build before it's published

I can't think of a reason it would need to be build otherwise.

**Comment by sibelius** [comment]
we can have watch for testing

**Comment by reergymerej** [comment]
start script added, watch doesn't seem to be needed
